/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    BahrainProfileCard: typeof import('./src/components/employees/BahrainProfileCard.vue')['default']
    Breadcrumbs: typeof import('./src/components/ui/Breadcrumbs.vue')['default']
    ChartCard: typeof import('./src/components/ui/ChartCard.vue')['default']
    CompanySwitcher: typeof import('./src/components/ui/CompanySwitcher.vue')['default']
    ComplianceScore: typeof import('./src/components/ui/ComplianceScore.vue')['default']
    CountryMetrics: typeof import('./src/components/ui/CountryMetrics.vue')['default']
    DataTable: typeof import('./src/components/ui/DataTable.vue')['default']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ui/ErrorState.vue')['default']
    ExpiryList: typeof import('./src/components/ui/ExpiryList.vue')['default']
    FilterBar: typeof import('./src/components/ui/FilterBar.vue')['default']
    IssueList: typeof import('./src/components/ui/IssueList.vue')['default']
    KpiCard: typeof import('./src/components/ui/KpiCard.vue')['default']
    KuwaitProfileCard: typeof import('./src/components/employees/KuwaitProfileCard.vue')['default']
    LoadingState: typeof import('./src/components/ui/LoadingState.vue')['default']
    OmanProfileCard: typeof import('./src/components/employees/OmanProfileCard.vue')['default']
    PageHeader: typeof import('./src/components/ui/PageHeader.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    QatarProfileCard: typeof import('./src/components/employees/QatarProfileCard.vue')['default']
    QuickActions: typeof import('./src/components/ui/QuickActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaudiProfileCard: typeof import('./src/components/employees/SaudiProfileCard.vue')['default']
    SearchInput: typeof import('./src/components/ui/SearchInput.vue')['default']
    SectionCard: typeof import('./src/components/ui/SectionCard.vue')['default']
    ShortcutList: typeof import('./src/components/ui/ShortcutList.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StatusBadge: typeof import('./src/components/ui/StatusBadge.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
    UAEProfileCard: typeof import('./src/components/employees/UAEProfileCard.vue')['default']
  }
}
